debug-mode = true
prover-buffer-size = {{ .agglayer_prover_buffer_size }}

{{if and (ne .zkevm_fork_id "9") (ne .zkevm_fork_id "11")}}
# Only supported by fork 12+
mock-verifier = {{.mock_verifier}}
{{end}}

[full-node-rpcs]
{{- if eq .sequencer_type "op-reth" }}
1 = "{{.op_el_rpc_url}}"
{{- else }}
1 = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.http_rpc_port_number}}"
{{- end }}

[l2]
rpc-timeout = "45s"

[proof-signers]
1 = "{{.l2_sequencer_address}}"

[log]
level = "{{.log_level}}"
outputs = ["stderr"]
format = "{{.log_format}}"

[rpc]
grpc-port = {{.agglayer_grpc_port}}
readrpc-port = {{.agglayer_readrpc_port}}
{{- if ne .agglayer_admin_port "0" }}
admin-port = {{.agglayer_admin_port}}
{{- end }}
host = "0.0.0.0"
request-timeout = "3m"
max-request-body-size = 104857600
max-response-body-size = 104857600

[grpc]
max-decoding-message-size = 104857600
max-encoding-message-size = 104857600

[outbound.rpc.settle-tx]
max-retries = 3
retry-interval = "7s"
confirmations = 1

[outbound.rpc.settle-cert]
max-retries = 3
retry-interval = "7s"
confirmations = 1

[l1]
chain-id = {{.l1_chain_id}}
node-url = "{{.l1_rpc_url}}"
ws-node-url = "{{.l1_ws_url}}"
rollup-manager-contract = "{{.rollup_manager_address}}"
polygon-zkevm-global-exit-root-v2-contract = "{{.l1_ger_address}}"
rpc-timeout = "45s"

[auth.local]
private-keys = [
    { path = "/etc/agglayer/aggregator.keystore", password = "{{.l2_keystore_password}}" },
]

[telemetry]
prometheus-addr = "0.0.0.0:{{.prometheus_port}}"

[rate-limiting]
send-tx = "unlimited"

[rate-limiting.network]

[epoch.block-clock]
epoch-duration = 15
genesis-block = {{.rollup_manager_block_number}}

[shutdown]
runtime-timeout = "5s"

[certificate-orchestrator]
input-backpressure-buffer-size = {{ .agglayer_input_backpressure_buffer_size }}

{{- if eq .agglayer_prover_primary_prover "network-prover" }}
[certificate-orchestrator.prover.sp1-network]
{{- else if eq .agglayer_prover_primary_prover "cpu-prover" }}
[certificate-orchestrator.prover.sp1-local]
{{- else }}
[certificate-orchestrator.prover.sp1-mock]
{{- end }}

[storage]
db-path = "/etc/agglayer/storage"

{{- if eq .agglayer_prover_primary_prover "network-prover" }}
[prover.network-prover]
proving-timeout = "5m"
sp1-cluster-endpoint = "{{.sp1_cluster_endpoint}}"
{{- else if eq .agglayer_prover_primary_prover "cpu-prover" }}
[prover.cpu-prover]
max-concurrency-limit = {{ .agglayer_cpu_prover_max_concurrency_limit }}
proving-timeout = "{{ .agglayer_cpu_prover_proving_timeout }}"
{{- else }}
[prover.mock-prover]
proving-timeout = "5m"
proving-request-timeout = "300s"
{{- end }}
